### ISSUE TITLE
Throw 'Error: Please set height and width for the chart element'

### ISSUE THREAD

**Issue by itryapitsin** [chinmaymk/angular-charts#103]
Throw 'Error: Please set height and width for the chart element' when contained in inactive tab

**Comment by nyeinchanjob** [comment]
hello, I got same error. and I put chart div element into md-sidenav. if I put outside of md-sidenav, chart work well. So how to fix it.

**Comment by rockaravind** [comment]
Hello, I'm still getting this issue with angular versions 1.4.3. Is there a permanent fix for this somewhere.
Please help me to resolve this issue :
Error: Please set height and width for the chart element

**Comment by nurexmet** [comment]
Would you have a full example, preferably on jsbin or similar? This works for me using the line chart example in examples/charts.html and adding height="50" to the markup:

<canvas id="line" class="chart chart-line chart-xl" data="data" 
  labels="labels" legend="true" click="onClick" series="series" 
  height="50">
</canvas>

**Comment by nurexmet** [comment]
<div class="panel-heading" ng-bind="bigTitle"></div>
					<canvas id="bar" class="chart chart-bar"
					  chart-data="bigData" chart-labels="labelsLine"  chart-legend="true" chart-series="seriesBig"  height="70">
					</canvas>
				</div>

**Comment by johnnyzh82** [comment]
I have same issue, what is the solution of this issue?

**Comment by azain** [comment]
I am getting the same error. I tried using ng-if to delay the rendering of the chart until the data is present, but I am still getting the same error!
