### ISSUE TITLE
In case chart height is not set via CSS, gives an error

### ISSUE THREAD

**Issue by bebraw** [chinmaymk/angular-charts#12]
In case chart height is not set, it is very easy to end up with this D3 error:

```
Error: Invalid negative value for <svg> attribute height="-18" 
```

You might want to add a warning there to make the library nicer to use.

**Comment by technotomahi** [comment]
I have looked at the [plunker](http://plnkr.co/edit/T9J7bz?p=preview) and tried to fork this with AngularJS v1.4.6 (It was using AngularJS v1.2.2) then its not working. 

Can any one guide here if it is working on latest angularjs versions
