### ISSUE TITLE
Possible to remove extra padding/margin on right side of graphs?

### ISSUE THREAD

**Issue by atentis** [chinmaymk/angular-charts#161]
Hello,

I dont think this is necessarly an issue but I am trying to remove the excesses margin or padding that is on the right side of the graphs. The green border is the actual line chart class and not a containing div. I have gone into the lineChart function and adjusting the right margin does not seem to help. Any help on how I can eliminate this extra white space would be greatly appreciated!

![image](https://cloud.githubusercontent.com/assets/8903400/4903133/5530d616-643e-11e4-8ebc-14e3bd16947a.png)

function lineChart() {
        var margin = {
            top: 0,
            right: 0,
            bottom: 20,
            left: 40
          };
        width -= margin.left + margin.right;
        height -= margin.top + margin.bottom;

**Comment by robations** [comment]
I think this is fixed now? In the config, set `legend: { display: false }`
