### ISSUE TITLE
Ability to redraw chart when data changes?

### ISSUE THREAD

**Issue by atentis** [chinmaymk/angular-charts#164]
I have a multi-select that allows the user to change the data which fires an ng-change. The ng-change will get new data but the chart never redraws. It looks like even though ac-data has new data the only way the chart will redraw (run init code) is if ac-chart changes. Is there currently a way I can redraw if only the data changes? If not can this be added as a feature? 

Edit: I have added a plunk showing this. Even if you were to make the ng-change a click event with simple dropdown you would have the same issue. The user cant change data without making the ac-chart directive load again. 

http://plnkr.co/edit/gscm4Y?p=preview

**Comment by sajeetharan** [comment]
how did you made it to work?  Here is my question on it http://stackoverflow.com/questions/27792091/how-to-bind-data-of-angular-charts-dynamically
