### ISSUE TITLE
Error: Please set height and width for the chart element

### ISSUE THREAD

**Issue by prathyushabandela** [chinmaymk/angular-charts#179]
it is throwing Error: Please set height and width for the chart element..
But when i set width and height in css/html then the page is crashing...

**Comment by joe-singer** [comment]
2.7 is causing the browser to freeze and crash. I installed 2.6 and the issue was resolved.

**Comment by PuKoren** [comment]
I also have the issue, using bootstrap and ng-hide/show

**Comment by cementovoz** [comment]
in 2.6 i also have a Error:  Please set height and width for the chart element..
in 2.7 with  waitForHeightAndWidth:true - browser to freeze.
using bootstrap modal for view charts

**Comment by srph** [comment]
The same happens for me. I might have to revert to 2.5.

**Comment by GentooXativa** [comment]
Reverting to 0.2.6 fixed the issue for me too.

**Comment by FabVillegas** [comment]
Bumping, 0.2.7 is the problem.

**Comment by mojobiri** [comment]
Have the same problem with 0.2.7 version.

**Comment by tmatma** [comment]
Same here, worked after switching `0.2.7`to `0.2.6`. Thanks for heads up!

**Comment by cmbirk** [comment]
I still get the issue when reverting to 0.2.6 and 0.2.5.  I'm using angular~1.3.11

**Comment by srph** [comment]
Are you sure you are reverting to 0.2.6? May you provide us your ```bower.json```?

**Comment by cmbirk** [comment]
```
{
  ...
  "resolutions": {
    "jquery": "~2.0.3"
  },
  "dependencies": {
    "angular": "~1.3.11",
    "angular-ui": "~0.4.0",
    "jquery": "~2.1.3",
    "angular-ui-router": "~0.2.13",
    "bootstrap": "~3.3.2",
    "angular-charts": "0.2.6"
  }
}
```

**Comment by srph** [comment]
That's weird. Have you tried running ```bower update``` or re-installing the bower dependencies?

**Comment by vvvvalvalval** [comment]
Same issue. Just installed angular-charts via bower for the first time, and struggled for an hour before I found this. Reverting to 0.2.6 did it.

**Comment by prathyushabandela** [comment]
Thank you guys... its working fine now..

**Comment by HadrienPierart** [comment]
Same here. Thx guys and thx google for pointing me here with the search "angular charts page freeze".
For some reason I also had to set a width in pixel and not in %...

**Comment by djabif** [comment]
Thanks guys!

**Comment by lvarayut** [comment]
Thanks so much. I wasted 3 hours before finding this thread. Reverting back to `2.6.0` did the trick!

**Comment by ronny332** [comment]
0.2.6 does work for me, too.

the reason for all of this seem to be jquery and a fix is already available:
https://github.com/moumar/angular-charts/commit/487205efd2584c5390be897da8aa9260ae7a667d

I've patched version 0.2.7 for testing and it works. Hopefully there will be a bower update later on.

**Comment by ee0pdt** [comment]
ditto re: 0.2.6 - google lead me here....

**Comment by jasonz1987** [comment]
tks
