### ISSUE TITLE
Angular-charts inside ionic

### ISSUE THREAD

**Issue by afontang** [chinmaymk/angular-charts#20]
I have been developing with ionic framework (http://ionicframework.com/) v0.9.17 and angular-charts worked inside a tag. 

Today I migrated to Ionic, v0.9.21 and angular-charts thows an error: TypeError: Object [object Object] has no method 'width'
 at e (http://localhost/MP2JSMobile/Ionic2/lib/js/angular-charts.min.js:1:10690)

Any idea what's happening? 

Regards,

Andrés

**Comment by zhendong590** [comment]
thanks a lot!
