### ISSUE TITLE
Please set height and width for the chart element

### ISSUE THREAD

**Issue by StevenStar** [chinmaymk/angular-charts#204]
Error: Please set height and width for the chart element
    at validateHeightAndWidth (http://127.0.0.1:9000/bower_components/angular-charts/dist/angular-charts.js:138:15)

**Comment by rdmclin2** [comment]
put the following in your css file
```
.chart {
 width: 500px;
 height: 500px;
}
```

**Comment by atentis** [comment]
@StevenStar  It looks like @rdmclin2 has what you were missing. Please close this issue.
