### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pageX' of undefined 

### ISSUE THREAD

**Issue by kanchansrivastava** [chinmaymk/angular-charts#22]
This error occurs when chart type is pie

**Comment by PuKoren** [comment]
I have the issue on latest version when using a chart type line, and mouse-hovering
Uncaught TypeError: Cannot read property 'pageX' of undefined

**Comment by melges-morgen** [comment]
Hi, i am have this issue in the latest version when using line charts. 

The error caught on mouse over event at _angular-charts.js:808_ becouse **event** is undefined:
```
function updateToolTip(d, event) {
        if (scope.$tooltip) {
          scope.$tooltip.css({
            left: event.pageX + 20 + 'px',
            top: event.pageY - 30 + 'px'
          });
        }
}
```
which is called from _angular-charts.js:468_:
```
updateToolTip(d3.event);
```
I think that changing
```
updateToolTip(d3.event); 
```
to 
```
updateToolTip(d3, d3.event);
``` 
will fix the issue.

Thanks for attention.
