### ISSUE TITLE
Allow the ac-chart element to change width/height with the chart responding properly

### ISSUE THREAD

**Issue by wilfriedvanasten** [chinmaymk/angular-charts#27]
It would be very cool if the charts were able to properly respond to the element the directive is applied to changing its height or width. This is (as far as I can see) currently not happening. It seems to me this is because the totalWidth and totalHeight are fixed from the moment the directive is compiled. 

It may be possible for the height and width to be undefined initially by design waiting for some data so the element should be able to handle those cases as well (So not as in #12)

**Comment by lvarayut** [comment]
Facing the same issue. It overlapped on a small device. Do you have any progress on this issue?
