### ISSUE TITLE
Is it supposed to work with promises ?

### ISSUE THREAD

**Issue by Marsup** [chinmaymk/angular-charts#35]
Hello,

I have tried to use it with promises but it won't work (exemple: http://plnkr.co/edit/qzZd7tHAIeXRZg4YyzQB?p=preview).
I'm not sure this library is able to work with promises or not, if it is I don't see my mistake, if it's not, did anyone find a work around to have such behavior ?

**Comment by m4cx** [comment]
Would it not be a great effort, if angular-charts would wait until promises are resolved instead of tweaking at controller or in view to get this working right?
