### ISSUE TITLE
Resizing

### ISSUE THREAD

**Issue by jasoncmcg** [chinmaymk/angular-charts#99]
-1: I love angular-charts, it is my favorite
-2: I am having a problem with resizing. 
The charts ignore the boundaries of the container and overflow instead of resize.
As a note, I am using angular-ui bootstrap.
section class="col-sm-6 panel panel-default" data-ng-controller="ChartOne"
    div class="panel-body"
        select ng-model="chartType"
            option value="pie">Pie /option
            option value="bar">Bar /option
            option value="line">Line /option
            option value="point">Point /option
            option value="area">Area /option
        /select
        span ng-show="chartType === 'pie'"
            label for="innerRadius">Radius: /label
            input ng-model="config1.innerRadius" type="number" id="innerRadius" /
        /span
        div ac-chart="chartType" ac-data="chartData" ac-config="config" id='chart' class='chart' /div
    /div>
/section>

![image](https://cloud.githubusercontent.com/assets/695352/3497740/51d6099a-05ee-11e4-8e81-db8afd1996af.png)

**Comment by sajeetharan** [comment]
can you share the whole config?
